// <auto-generated />
using System;
using CommunityEventManagement.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunityEventManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626172019_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_Events_StartDate");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("IX_Events_VenueId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.EventActivity", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderInEvent")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "ActivityId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EventId1");

                    b.ToTable("EventActivities");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.EventVenue", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("EventId", "VenueId");

                    b.HasIndex("EventId1");

                    b.HasIndex("VenueId");

                    b.HasIndex("EventId", "VenueId")
                        .IsUnique()
                        .HasDatabaseName("IX_EventVenues_EventId_VenueId");

                    b.ToTable("EventVenues");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("UserType").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParticipantId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_Registrations_EventId");

                    b.HasIndex("EventId1");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("IX_Registrations_ParticipantId");

                    b.HasIndex("ParticipantId1");

                    b.HasIndex("ParticipantId", "EventId")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.AppUser", b =>
                {
                    b.HasBaseType("CommunityEventManagement.Domain.Entities.Person");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("AppUser");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Administrator", b =>
                {
                    b.HasBaseType("CommunityEventManagement.Domain.Entities.AppUser");

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Participant", b =>
                {
                    b.HasBaseType("CommunityEventManagement.Domain.Entities.AppUser");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Participants_Email");

                    b.HasDiscriminator().HasValue("Participant");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.EventActivity", b =>
                {
                    b.HasOne("CommunityEventManagement.Domain.Entities.Activity", "Activity")
                        .WithMany("EventActivities")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CommunityEventManagement.Domain.Entities.Event", "Event")
                        .WithMany("EventActivitiesCollection")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommunityEventManagement.Domain.Entities.Event", null)
                        .WithMany("EventActivities")
                        .HasForeignKey("EventId1");

                    b.Navigation("Activity");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.EventVenue", b =>
                {
                    b.HasOne("CommunityEventManagement.Domain.Entities.Event", "Event")
                        .WithMany("EventVenuesCollection")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommunityEventManagement.Domain.Entities.Event", null)
                        .WithMany("EventVenues")
                        .HasForeignKey("EventId1");

                    b.HasOne("CommunityEventManagement.Domain.Entities.Venue", "Venue")
                        .WithMany("EventVenues")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Registration", b =>
                {
                    b.HasOne("CommunityEventManagement.Domain.Entities.Event", "Event")
                        .WithMany("RegistrationsCollection")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommunityEventManagement.Domain.Entities.Event", null)
                        .WithMany("Registrations")
                        .HasForeignKey("EventId1");

                    b.HasOne("CommunityEventManagement.Domain.Entities.Participant", "Participant")
                        .WithMany("RegistrationsCollection")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommunityEventManagement.Domain.Entities.Participant", null)
                        .WithMany("Registrations")
                        .HasForeignKey("ParticipantId1");

                    b.Navigation("Event");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Activity", b =>
                {
                    b.Navigation("EventActivities");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventActivities");

                    b.Navigation("EventActivitiesCollection");

                    b.Navigation("EventVenues");

                    b.Navigation("EventVenuesCollection");

                    b.Navigation("Registrations");

                    b.Navigation("RegistrationsCollection");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Venue", b =>
                {
                    b.Navigation("EventVenues");
                });

            modelBuilder.Entity("CommunityEventManagement.Domain.Entities.Participant", b =>
                {
                    b.Navigation("Registrations");

                    b.Navigation("RegistrationsCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
